### ISSUE TITLE
404, File Not Found!

### ISSUE THREAD

**Issue by hydropunk69** [Fornaxian/pixeldrain_web#9] opened 2023-06-16 13:51 UTC
Hello, thank you very much for Pixeldrain.

I don't know if this is the place to report the following bug.

When I upload a file via API sometimes the file cannot be accessed with the url returned by the API, the file even appears in my account but if I click on it I get error 404.

thank you so much.

![image](https://github.com/Fornaxian/pixeldrain_web/assets/6971339/d7a66369-4374-406a-bfbe-317af1e91ff7)

`https://pixeldrain.com/u/i6gEbkWZ`

**Comment by Fornax96** [comment] 2023-06-21 08:30
This was caused by a database synchronization issue. The cluster in the USA had a database failure which caused some data to get lost there while they were still available in the Europe region. Should be fixed now.

**Closed by Fornax96** 2023-06-21 08:30 UTC
